== How It Works


## The Aragon OSx DAO Framework

The Aragon OSx protocol is a DAO framework structured as follows:

image::../../_/images/aragon-os-framework-overview.drawio.svg[align="center"]

Overview of the Aragon OSx protocol with its structural components and their responsibilities: the governance layer constituted by the framework DAO, the code layer including the framework and core contracts, which depends on external libraries and services

### Code Layer

The foundation of the Aragon OSx protocol is the **code layer** constituted by the core and framework related contracts.
The xref:how-it-works/core/index.adoc[core contracts] provide the core primitives intended to be used by users and implemented by developers of the DAO framework.
The xref:how-it-works/framework/index.adoc[framework contracts] provide the infrastructure to easily create and manage your DAOs and plugins easy.
Both are built on top of external dependencies, most notably the link:https://www.openzeppelin.com/contracts[OpenZeppelin] and the link:https://docs.ens.domains/[Ethereum Name Service (ENS)] contracts.

The core and framework contracts are free to use, and no additional fees are charged.

### Governance Layer

To govern the framework infrastructure, an Aragon OSx [Framework DAO](./03-framwork-dao.md) is deployed constituting the **governance layer** of the Aragon OSx protocol.

In the next sections, you will learn more about the individual components of the framework.
