import * as abis from './generated/abis';

const {
  actionExecuteAbi,
  callbackHandlerAbi,
  callbackHandlerMockHelperAbi,
  daoAbi,
  daoFactoryAbi,
  daoRegistryAbi,
  ensSubdomainRegistrarAbi,
  erc1155MockAbi,
  erc20MockAbi,
  erc721MockAbi,
  gasConsumerAbi,
  ieip4824Abi,
  iPluginRepoAbi,
  interfaceBasedRegistryAbi,
  interfaceBasedRegistryMockAbi,
  permissionConditionMockAbi,
  permissionManagerAbi,
  permissionManagerTestAbi,
  placeholderSetupAbi,
  pluginCloneableSetupV1MockAbi,
  pluginCloneableSetupV1MockBadAbi,
  pluginCloneableSetupV2MockAbi,
  pluginCloneableV1MockAbi,
  pluginCloneableV1MockBadAbi,
  pluginCloneableV2MockAbi,
  pluginRepoAbi,
  pluginRepoFactoryAbi,
  pluginRepoRegistryAbi,
  pluginSetupProcessorAbi,
  pluginUupsUpgradeableSetupV1MockAbi,
  pluginUupsUpgradeableSetupV1MockBadAbi,
  pluginUupsUpgradeableSetupV2MockAbi,
  pluginUupsUpgradeableSetupV3MockAbi,
  pluginUupsUpgradeableSetupV4MockAbi,
  pluginUupsUpgradeableV1MockAbi,
  pluginUupsUpgradeableV2MockAbi,
  pluginUupsUpgradeableV3MockAbi,
  pluginV1MockAbi,
  protocolVersionMockAbi,
  registryUtilsAbi,
} = abis;

export {
  actionExecuteAbi as ActionExecuteAbi,
  callbackHandlerAbi as CallbackHandlerAbi,
  callbackHandlerMockHelperAbi as CallbackHandlerMockHelperAbi,
  daoAbi as DAOAbi,
  daoFactoryAbi as DAOFactoryAbi,
  daoRegistryAbi as DAORegistryAbi,
  ensSubdomainRegistrarAbi as ENSSubdomainRegistrarAbi,
  erc1155MockAbi as ERC1155MockAbi,
  erc20MockAbi as ERC20MockAbi,
  erc721MockAbi as ERC721MockAbi,
  gasConsumerAbi as GasConsumerAbi,
  ieip4824Abi as IEIP4824Abi,
  iPluginRepoAbi as IPluginRepoAbi,
  interfaceBasedRegistryAbi as InterfaceBasedRegistryAbi,
  interfaceBasedRegistryMockAbi as InterfaceBasedRegistryMockAbi,
  permissionConditionMockAbi as PermissionConditionMockAbi,
  permissionManagerAbi as PermissionManagerAbi,
  permissionManagerTestAbi as PermissionManagerTestAbi,
  placeholderSetupAbi as PlaceholderSetupAbi,
  pluginCloneableSetupV1MockAbi as PluginCloneableSetupV1MockAbi,
  pluginCloneableSetupV1MockBadAbi as PluginCloneableSetupV1MockBadAbi,
  pluginCloneableSetupV2MockAbi as PluginCloneableSetupV2MockAbi,
  pluginCloneableV1MockAbi as PluginCloneableV1MockAbi,
  pluginCloneableV1MockBadAbi as PluginCloneableV1MockBadAbi,
  pluginCloneableV2MockAbi as PluginCloneableV2MockAbi,
  pluginRepoAbi as PluginRepoAbi,
  pluginRepoFactoryAbi as PluginRepoFactoryAbi,
  pluginRepoRegistryAbi as PluginRepoRegistryAbi,
  pluginSetupProcessorAbi as PluginSetupProcessorAbi,
  pluginUupsUpgradeableSetupV1MockAbi as PluginUUPSUpgradeableSetupV1MockAbi,
  pluginUupsUpgradeableSetupV1MockBadAbi as PluginUUPSUpgradeableSetupV1MockBadAbi,
  pluginUupsUpgradeableSetupV2MockAbi as PluginUUPSUpgradeableSetupV2MockAbi,
  pluginUupsUpgradeableSetupV3MockAbi as PluginUUPSUpgradeableSetupV3MockAbi,
  pluginUupsUpgradeableSetupV4MockAbi as PluginUUPSUpgradeableSetupV4MockAbi,
  pluginUupsUpgradeableV1MockAbi as PluginUUPSUpgradeableV1MockAbi,
  pluginUupsUpgradeableV2MockAbi as PluginUUPSUpgradeableV2MockAbi,
  pluginUupsUpgradeableV3MockAbi as PluginUUPSUpgradeableV3MockAbi,
  pluginV1MockAbi as PluginV1MockAbi,
  protocolVersionMockAbi as ProtocolVersionMockAbi,
  registryUtilsAbi as RegistryUtilsAbi,
};
