import * as DAO from '../contracts/artifacts/src/core/dao/DAO.sol/DAO.json';
import * as PermissionManager from '../contracts/artifacts/src/core/permission/PermissionManager.sol/PermissionManager.json';
import * as DAOFactory from '../contracts/artifacts/src/framework/dao/DAOFactory.sol/DAOFactory.json';
import * as DAORegistry from '../contracts/artifacts/src/framework/dao/DAORegistry.sol/DAORegistry.json';
import * as PluginRepo from '../contracts/artifacts/src/framework/plugin/repo/PluginRepo.sol/PluginRepo.json';
import * as PluginRepoFactory from '../contracts/artifacts/src/framework/plugin/repo/PluginRepoFactory.sol/PluginRepoFactory.json';
import * as PluginRepoRegistry from '../contracts/artifacts/src/framework/plugin/repo/PluginRepoRegistry.sol/PluginRepoRegistry.json';
import * as PluginSetupProcessor from '../contracts/artifacts/src/framework/plugin/setup/PluginSetupProcessor.sol/PluginSetupProcessor.json';
import * as viemAbi from './generated/abis';

export const {
  actionExecuteAbi,
  callbackHandlerAbi,
  callbackHandlerMockHelperAbi,
  daoAbi,
  daoFactoryAbi,
  daoRegistryAbi,
  ensSubdomainRegistrarAbi,
  erc1155MockAbi,
  erc20MockAbi,
  erc721MockAbi,
  gasConsumerAbi,
  ieip4824Abi,
  iPluginRepoAbi,
  interfaceBasedRegistryAbi,
  interfaceBasedRegistryMockAbi,
  permissionConditionMockAbi,
  permissionManagerAbi,
  permissionManagerTestAbi,
  placeholderSetupAbi,
  pluginCloneableSetupV1MockAbi,
  pluginCloneableSetupV1MockBadAbi,
  pluginCloneableSetupV2MockAbi,
  pluginCloneableV1MockAbi,
  pluginCloneableV1MockBadAbi,
  pluginCloneableV2MockAbi,
  pluginRepoAbi,
  pluginRepoFactoryAbi,
  pluginRepoRegistryAbi,
  pluginSetupProcessorAbi,
  pluginUupsUpgradeableSetupV1MockAbi,
  pluginUupsUpgradeableSetupV1MockBadAbi,
  pluginUupsUpgradeableSetupV2MockAbi,
  pluginUupsUpgradeableSetupV3MockAbi,
  pluginUupsUpgradeableSetupV4MockAbi,
  pluginUupsUpgradeableV1MockAbi,
  pluginUupsUpgradeableV2MockAbi,
  pluginUupsUpgradeableV3MockAbi,
  pluginV1MockAbi,
  protocolVersionMockAbi,
  registryUtilsAbi,
} = viemAbi;

export const json = {
  DAO,
  PermissionManager,
  DAOFactory,
  DAORegistry,
  PluginRepo,
  PluginRepoFactory,
  PluginRepoRegistry,
  PluginSetupProcessor,
};

export const viem = viemAbi;
export default {
  json,
  viem,
  DAO,
  PermissionManager,
  DAOFactory,
  DAORegistry,
  PluginRepo,
  PluginRepoFactory,
  PluginRepoRegistry,
  PluginSetupProcessor,
  actionExecuteAbi,
  callbackHandlerAbi,
  callbackHandlerMockHelperAbi,
  daoAbi,
  daoFactoryAbi,
  daoRegistryAbi,
  ensSubdomainRegistrarAbi,
  erc1155MockAbi,
  erc20MockAbi,
  erc721MockAbi,
  gasConsumerAbi,
  ieip4824Abi,
  iPluginRepoAbi,
  interfaceBasedRegistryAbi,
  interfaceBasedRegistryMockAbi,
  permissionConditionMockAbi,
  permissionManagerAbi,
  permissionManagerTestAbi,
  placeholderSetupAbi,
  pluginCloneableSetupV1MockAbi,
  pluginCloneableSetupV1MockBadAbi,
  pluginCloneableSetupV2MockAbi,
  pluginCloneableV1MockAbi,
  pluginCloneableV1MockBadAbi,
  pluginCloneableV2MockAbi,
  pluginRepoAbi,
  pluginRepoFactoryAbi,
  pluginRepoRegistryAbi,
  pluginSetupProcessorAbi,
  pluginUupsUpgradeableSetupV1MockAbi,
  pluginUupsUpgradeableSetupV1MockBadAbi,
  pluginUupsUpgradeableSetupV2MockAbi,
  pluginUupsUpgradeableSetupV3MockAbi,
  pluginUupsUpgradeableSetupV4MockAbi,
  pluginUupsUpgradeableV1MockAbi,
  pluginUupsUpgradeableV2MockAbi,
  pluginUupsUpgradeableV3MockAbi,
  pluginV1MockAbi,
  protocolVersionMockAbi,
  registryUtilsAbi,
};
