#!/usr/bin/env bash

# Exit on error
set -e

# Constants
CONTRACTS_FOLDER="../contracts"
TARGET_ABI_FILE="./src/abi.ts"

# Move into contracts package and install dependencies
cd $CONTRACTS_FOLDER

yarn install && yarn build

# Move back to artifacts package
cd - > /dev/null

# Wipe the destination file
echo "// NOTE: Do not edit this file. It is generated automatically and it will be eventually wiped." > $TARGET_ABI_FILE

# Extract the abi field and create a TS file
CONTRACT_ARTIFACTS=$(ls \
    $CONTRACTS_FOLDER/artifacts/src/core/*/*/*.json \
    $CONTRACTS_FOLDER/artifacts/src/framework/*/*/*.json \
    $CONTRACTS_FOLDER/artifacts/src/framework/*/*/*/*.json \
    | grep -v ".dbg." \
    | grep -v utils
)
for FILE in $CONTRACT_ARTIFACTS
do
    SRC_FILE_NAME=$(basename $FILE)

    # Backwards compatible exports with abi and bytecode
    ABI=$(node -e "console.log(JSON.stringify(JSON.parse(fs.readFileSync('$FILE').toString()).abi))")
    BYTECODE=$(node -e "console.log(JSON.parse(fs.readFileSync('$FILE').toString()).bytecode || '')")
    CONTRACT_NAME=${SRC_FILE_NAME%".json"}

    echo "const ${CONTRACT_NAME}ABI = $ABI as const;" >> $TARGET_ABI_FILE
    if [ "$BYTECODE" == "0x" -o "$BYTECODE" == "" ]; then
        echo "export const $CONTRACT_NAME = { abi: ${CONTRACT_NAME}ABI, bytecode: null };" >> $TARGET_ABI_FILE
    else
        echo "const ${CONTRACT_NAME}Bytecode = \"$BYTECODE\";" >> $TARGET_ABI_FILE
        echo "export const $CONTRACT_NAME = { abi: ${CONTRACT_NAME}ABI, bytecode: ${CONTRACT_NAME}Bytecode };" >> $TARGET_ABI_FILE
    fi

    echo "" >> $TARGET_ABI_FILE
done

# Common interfaces JSON ABI
EXTRA_CONTRACT_ABI_FILES=$(ls \
    $CONTRACTS_FOLDER/artifacts/@aragon/osx-commons-contracts/src/dao/*.sol/*.json \
    $CONTRACTS_FOLDER/artifacts/@aragon/osx-commons-contracts/src/executors/*.sol/*.json \
    $CONTRACTS_FOLDER/artifacts/@aragon/osx-commons-contracts/src/permission/*/*.sol/*.json \
    $CONTRACTS_FOLDER/artifacts/@aragon/osx-commons-contracts/src/plugin/*.sol/*.json \
    $CONTRACTS_FOLDER/artifacts/@aragon/osx-commons-contracts/src/plugin/setup/*.sol/*.json \
    $CONTRACTS_FOLDER/artifacts/@aragon/osx-commons-contracts/src/utils/versioning/*.sol/*.json \
    | grep -v ".dbg."
)

# Shipping the common interfaces as well
for FILE in $EXTRA_CONTRACT_ABI_FILES
do
    SRC_FILE_NAME=$(basename $FILE)

    ABI=$(node -e "console.log(JSON.stringify(JSON.parse(fs.readFileSync('$FILE').toString()).abi))")
    BYTECODE=$(node -e "console.log(JSON.parse(fs.readFileSync('$FILE').toString()).bytecode || '')")
    CONTRACT_NAME=${SRC_FILE_NAME%".json"}

    echo "const ${CONTRACT_NAME}ABI = $ABI as const;" >> $TARGET_ABI_FILE
    if [ "$BYTECODE" == "0x" -o "$BYTECODE" == "" ]; then
        echo "export const $CONTRACT_NAME = { abi: ${CONTRACT_NAME}ABI, bytecode: null };" >> $TARGET_ABI_FILE
    else
        echo "const ${CONTRACT_NAME}Bytecode = \"$BYTECODE\";" >> $TARGET_ABI_FILE
        echo "export const $CONTRACT_NAME = { abi: ${CONTRACT_NAME}ABI, bytecode: ${CONTRACT_NAME}Bytecode };" >> $TARGET_ABI_FILE
    fi

    echo "" >> $TARGET_ABI_FILE
done

echo "ABI prepared: $TARGET_ABI_FILE"
