
analyze:
    create-group: true
    group-name: Core
    solc: 0.8.17
    remappings:
        - "@openzeppelin/=./node_modules/@openzeppelin/"
        - "@opengsn/=./node_modules/@opengsn/"
        - "@ensdomains/=./node_modules/@ensdomains/"
