[profile.default]
src = "src"
test = "test"
script = "scripts"
out = "out"
libs = ["lib"]
solc = "0.8.17"
optimizer = true
optimizer-runs = 2000
extra_output = ["storageLayout"]
# Allow forge scripts to write to ./artifacts/ (deployment outputs).
fs_permissions = [{ access = "write", path = "./artifacts" }]

[profile.ci]
fuzz = { runs = 512 }
