default: help

import 'lib/just-foundry/justfile'

# Build Asciidoc documentation from forge build artifacts.
[group('documentation')]
build-docs:
    forge build --ast
    GITHUB_REF="${GITHUB_REF:-main}" python3 scripts/build-docs.py

# Export every src/ contract's ABI as a TypeScript file under artifacts/abi/.
# Output: artifacts/abi/<ContractName>.ts (one per contract, including interfaces).
# Naming: `export const <contractName>Abi` (camel-case first letter).
# Uses an `abi/` subdir to avoid collision with just-foundry's `artifacts/`
# convention (deployment outputs land there).
[group('build')]
export-abi:
    #!/usr/bin/env bash
    set -euo pipefail
    forge build --quiet
    mkdir -p artifacts/abi
    rm -f artifacts/abi/*.ts
    count=0
    for sol in $(find src -type f -name "*.sol"); do
        file=$(basename "$sol")
        contract=$(basename "$sol" .sol)
        artifact="out/$file/$contract.json"
        [[ -f "$artifact" ]] || continue
        var=$(echo "$contract" | python3 -c "import sys; n=sys.stdin.read().strip(); print(n[0].lower() + n[1:] + 'Abi')")
        {
            echo "// Auto-generated by: just export-abi"
            echo "// Source: $sol"
            echo "// Do not edit manually."
            echo ""
            echo -n "export const $var = "
            jq -c '.abi' "$artifact" | python3 -c "import sys,json; print(json.dumps(json.load(sys.stdin), indent=2))" | head -c -1
            echo " as const;"
        } > "artifacts/abi/$contract.ts"
        count=$((count + 1))
    done
    echo "Exported $count ABIs to artifacts/abi/"
