version: '3'
services:
  hardhat-node:
    build:
      context: .
      dockerfile: hardhat.Dockerfile
    container_name: ${PROJECT_NAME:-local-subgraph}-hardhat-node
    ports:
      - 8545:${HARDHAT_PORT:-8545}
    networks:
      internal:
        aliases:
          - ${HARDHAT_HOST:-hardhat}

  ipfs:
    image: ipfs/kubo:${IPFS_VERSION:-v0.27.0}
    container_name: ${PROJECT_NAME:-local-subgraph}-ipfs
    command: ['daemon', '--migrate=true']
    ports:
      - 5001:${IPFS_PORT:-5001}
    volumes:
      - ${IPFS_VOLUME_DATA:-./data/ipfs}:/data/ipfs
    networks:
      internal:
        aliases:
          - ${IPFS_HOST:-ipfs}

  postgres:
    image: postgres:${POSTGRES_VERSION:-15.3-alpine}
    container_name: ${PROJECT_NAME:-local-subgraph}-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-graph-node}
      POSTGRES_USER: ${POSTGRES_USER:-graph-node}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-super-secure-password}
      PGDATA: '/var/lib/postgresql/data'
      POSTGRES_INITDB_ARGS: '-E UTF8 --locale=C'
    command: ['postgres', '-cshared_preload_libraries=pg_stat_statements']
    volumes:
      - ${POSTGRES_VOLUME_DATA:-./data/postgres}:/var/lib/postgresql/data
    networks:
      internal:
        aliases:
          - ${POSTGRES_HOST:-postgres}

  graph-node:
    image: graphprotocol/graph-node:${GRAPH_NODE_VERSION:-latest}
    container_name: ${PROJECT_NAME:-local-subgraph}-graph-node
    platform: linux/amd64
    depends_on:
      - ipfs
      - postgres
      - hardhat-node
    ports:
      - 8000:${GRAPH_NODE_SERVER_PORT:-8000}
      - 8001:${GRAPH_NODE_SERVER_WS_PORT:-8001}
      - 8020:${GRAPH_NODE_ADMIN_PORT:-8020}
      - 8030:${GRAPH_NODE_INDEX_NODE_SERVER_PORT:-8030}
      - 8040:${GRAPH_NODE_METRICS_PORT:-8040}
    environment:
      postgres_host: ${POSTGRES_HOST:-postgres}
      postgres_user: ${POSTGRES_USER:-graph-node}
      postgres_pass: ${POSTGRES_PASSWORD:-super-secure-password}
      postgres_db: ${POSTGRES_DB:-graph-node}
      ipfs: ${IPFS_HOST:-ipfs}:${IPFS_PORT:-5001}
      ethereum: localhost:http://${HARDHAT_HOST:-hardhat}:${HARDHAT_PORT:-8545}
      GRAPH_LOG: 'info'
    volumes:
      - ${GRAPH_NODE_VOLUME_DATA:-./data/graph-node}:/data
    networks:
      internal:
        aliases:
          - ${GRAPH_NODE_HOST:-graph-node}

networks:
  internal:
    name: ${PROJECT_NAME:-local-subgraph}
