version: '3'
services:
  hardhat-node:
    build: 
      context: .
      dockerfile: hardhat.Dockerfile 
    container_name: ${PROJECT_NAME}-hardhat-node
    ports:
      - 8545:${HARDHAT_PORT}
    networks:
      internal:
        aliases:
          - ${HARDHAT_HOST}

  ipfs:
    image: ipfs/kubo:${IPFS_VERSION}
    container_name: ${PROJECT_NAME}-ipfs
    command: ["daemon", "--migrate=true"]
    ports:
      - 5001:${IPFS_PORT}
    volumes:
      - ${IPFS_VOLUME_DATA}:/data/ipfs
    networks:
      internal:
        aliases:
          - ${IPFS_HOST}

  postgres:
    image: postgres:${POSTGRES_VERSION}
    container_name: ${PROJECT_NAME}-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: '/var/lib/postgresql/data'
      POSTGRES_INITDB_ARGS: '-E UTF8 --locale=C'
    command: ['postgres', '-cshared_preload_libraries=pg_stat_statements']
    volumes:
      - ${POSTGRES_VOLUME_DATA}:/var/lib/postgresql/data
    networks:
      internal:
        aliases:
          - ${POSTGRES_HOST}

  graph-node:
    image: graphprotocol/graph-node:${GRAPH_NODE_VERSION}
    container_name: ${PROJECT_NAME}-graph-node
    platform: linux/amd64
    depends_on:
      - ipfs
      - postgres
    ports:
      - 8000:${GRAPH_NODE_SERVER_PORT}
      - 8001:${GRAPH_NODE_SERVER_WS_PORT}
      - 8020:${GRAPH_NODE_ADMIN_PORT}
      - 8030:${GRAPH_NODE_INDEX_NODE_SERVER_PORT}
      - 8040:${GRAPH_NODE_METRICS_PORT}
    environment:
      postgres_host: ${POSTGRES_HOST}
      postgres_user: ${POSTGRES_USER}
      postgres_pass: ${POSTGRES_PASSWORD}
      postgres_db: ${POSTGRES_DB}
      ipfs: ${IPFS_HOST}:${IPFS_PORT}
      ethereum: localhost:http://${HARDHAT_HOST}:${HARDHAT_PORT}
      GRAPH_LOG: "info"
    volumes:
      - ${GRAPH_NODE_VOLUME_DATA}:/data
    networks:
      internal:
        aliases:
          - ${GRAPH_NODE_HOST}
    
networks:
  internal:
    name: ${PROJECT_NAME}
