= Framework - How Everything Connects

== The Infrastructure Running the Aragon OSx Protocol

The Aragon OSx protocol is composed of **framework-related contracts** creating and managing the **core contracts**. This includes the

- xref:how-it-works/framework/dao-creation/index.adoc[Creation of DAOs] and initial plugin configuration
- xref:how-it-works/framework/plugin-management/index.adoc[Management of plugins] which includes the

  - The setup in existing DAOs
  - The versioning of different implementations and respective setup contracts, UI, and related metadata

- xref:how-it-works/framework/ens-names.adoc[Assignment of ENS Names] to `Plugin` and `DAO` contracts created through the framework

An overview of the involved contracts and their interactions is shown below:

image::../../../_/images/optimized-svg/framework/aragon-os-infrastructure-core-overview.drawio.svg[align="center"]

In the following sections, you will learn more about the framework-related contracts of the Aragon OSx protocol.
