= Setting up a DAO

DAOs are decentralized autonomous organizations. They are a group of people managing on-chain assets through a set of smart contracts.

== What do you need to know in order to operate your DAO?

DAOs manage assets through collective decision-making mechanisms. Although a lot can be said of the social, behavioral aspects of operating a DAO, in this guide we will focus on the technical aspects.

In Aragon OSx, DAOs are a treasury and a permission management system - all other functionality is enabled through "capsules of opt-in functionality allowing the DAO to work in custom ways". These are called Plugins.

NOTE: Plugins are smart contracts which extend the functionality of what the DAO can do. They are able to execute actions on behalf of the DAO through permissions the DAO grants or revokes them.

Decision-making mechanisms are one example of Plugins. Treasury management, action bundles, or connections to other smart contracts are others.

== Walkthrough

In this section, we'll go through how to operate and maintain your DAO:

- xref:guide-set-up-dao/execute-actions.adoc[Executing actions on the DAO]
- xref:guide-set-up-dao/manage-dao-plugins.adoc[Managing a DAO's plugins]
- xref:guide-set-up-dao/custom-permission-condition.adoc[Writing custom permission conditions]
- xref:guide-set-up-dao/upgrade-dao.adoc[Upgrading your DAO]
- xref:guide-set-up-dao/keep-dao-safe.adoc[Keeping your DAO safe]
