= Plugin Repositories

== What are Plugin Repositories?

Each plugin has its own Plugin Repository, unique ENS name, and on-chain repository contract, the `PluginRepo`, in which different versions of the plugin are stored for reference using version tags constituted by a **release** and **build** number.

Different versions might contain:

- bug fixes
- new features
- breaking changes

`PluginRepo` contracts themselves, each associated with a different plugin, are registered in the Aragon 
OSx xref:how-it-works/framework/plugin-management/plugin-repo/plugin-repo-creation.adoc#the_pluginreporegistry_contract[PluginRepoRegistry]
and carry their own xrex:how-it-works/framework/ens-names.adoc[ENS name] that the creator chooses. 
The xref:how-it-works/framework/plugin-management/plugin-repo/plugin-repo-creation.adoc#the_pluginreporegistry_contract[PluginRepoRegistry] is described in the upcoming subsection.

image::../../../../../_/images/optimized-svg/plugins/plugin-repo-overview.drawio.svg[align="center"]


### The `PluginRepo` Contract

The `PluginRepo` contract versions the releases of a `Plugin`. The first version of a plugin is always published as release 1 and build 1 (version tag `1.1`).
When you publish the first plugin version, a new plugin repository is automatically created for you by the Aragon OSx protocol in which you are the maintainer. 
The creation process is described in the xref:how-it-works/framework/plugin-management/plugin-repo/plugin-repo-creation.adoc[plugin repo creation process] section.

The `PluginRepo` contract is link:https://eips.ethereum.org/EIPS/eip-1822[UUPS upgradeable], inherits from the xref:how-it-works/core/permissions/index.adoc[PermissionManager] 
and allows the maintainer of the repository to create new versions with the `createVersion` function:

```solidity"
/// @notice Creates a new plugin version as the latest build for an existing release number or the first build for a new release number for the provided `PluginSetup` contract address and metadata.
/// @param _release The release number.
/// @param _pluginSetupAddress The address of the plugin setup contract.
/// @param _buildMetadata The build metadata URI.
/// @param _releaseMetadata The release metadata URI.
function createVersion(
  uint8 _release,
  address _pluginSetup,
  bytes calldata _buildMetadata,
  bytes calldata _releaseMetadata
) external auth(address(this), MAINTAINER_PERMISSION_ID);
```

The function receives four input arguments:

1. The `_release` number to create the build for. If the release number exists already (e.g., release `1`), it is registered as the latest build (e.g., `1.3` if the previous build was `1.2`). If it is a new release number, the build number is `1` (e.g., `2.1`).
2. The address of `PluginSetup` contract internally referencing the implementation contract (to copy, proxy, or clone from it) and taking care of [installing, updating to, and uninstalling](../02-plugin-setup/index.md) this specific version.
3. The `_buildMetadata` URI pointing to a JSON file containing the UI data, setup data, and change description for this specific version.
4. The `_releaseMetadata` URI pointing to a JSON file containing the plugin name, description, as well as optional data such as images to be shown in the aragonApp frontend.

Other functions present in the contract allow you to query previous versions and to update the release metadata. For more details visit the [`PluginRepo` reference guide entry](../../../../03-reference-guide/framework/plugin/repo/PluginRepo.md). TODO:GIORGI

The `PluginRepo` is created for you when you publish the `PluginSetup` contract of your first version to the Aragon OSx protocol.