#!/usr/bin/env bash
# Generate src/abi.ts from forge build artifacts at the repo root.
# One consolidated TS file, one `export const <Contract>ABI = [...] as const;`
# entry per contract under `src/`. Bytecode and the legacy `<Contract>` class
# wrappers (deprecated since 1.4.x) are intentionally not emitted — consumers
# should import the ABI const directly and rely on deployed bytecode.

set -euo pipefail

# Pin sort order to byte-wise C collation so the generated file is identical
export LC_ALL=C

cd "$(dirname "$0")"
REPO_ROOT="$(cd .. && pwd)"
TARGET="src/abi.ts"

# Build at the repo root — uses the project's foundry.toml and remappings.
(cd "$REPO_ROOT" && forge build --quiet)

{
    echo "// Auto-generated by: bash prepare-abi.sh"
    echo "// Do not edit manually."
    echo ""
} > "$TARGET"

count=0
skipped=0
for sol in $(find "$REPO_ROOT/src" -type f -name "*.sol" | sort); do
    file=$(basename "$sol")
    contract=$(basename "$sol" .sol)
    artifact="$REPO_ROOT/out/$file/$contract.json"
    [[ -f "$artifact" ]] || continue

    abi=$(jq -c '.abi' "$artifact")
    # Skip files with no public surface (free-function files like auth.sol,
    # libraries with only internal/pure helpers, etc.). An empty ABI is useless
    # to consumers.
    if [[ "$abi" == "[]" ]]; then
        skipped=$((skipped + 1))
        continue
    fi

    {
        echo "export const ${contract}ABI = $abi as const;"
        echo ""
    } >> "$TARGET"
    count=$((count + 1))
done

echo "Exported $count ABIs to $TARGET (skipped $skipped with empty ABI)"
