= Non-Upgradeable Plugins

== Get Started with Non-Upgradeable Plugins

A Non-Upgradeable Plugin is a Plugin built on smart contracts that cannot be upgraded. This may or may not be what you want.

Some observations:

- Non-Upgradeable contracts are simpler to create, deploy, and manage.
- Instantiation is done via the `new` keyword or deployed via the link:https://eips.ethereum.org/EIPS/eip-1167[minimal proxy pattern (ERC-1167)].
- The storage is contained within each version. So if your plugin is dependent on state information from previous versions, 
you won't have access to it directly in upcoming versions, since every version is a blank new state. If this is a requirement 
for your project, we recommend you deploy an xref:how-to-guides/plugin-development/upgradeable-plugin/index.adoc[Upgradeable Plugin].

Before moving on with the Guide, make sure you've read our documentation on xref:how-to-guides/plugin-development/plugin-types.adoc[Choosing the Best Type for Your Plugin] to make sure you're selecting the right type of contract for your Plugin.

Up next, check out our guides on:

1. xref:how-to-guides/plugin-development/non-upgradeable-plugin/initialization.adoc[How to initialize Non-Upgradeable Plugins]
2. xref:how-to-guides/plugin-development/non-upgradeable-plugin/implementation.adoc[How to build the implementation of a Non-Upgradeable Plugin]
3. xref:how-to-guides/plugin-development/non-upgradeable-plugin/setup.adoc[How to build and deploy a Plugin Setup contract for a Non-Upgradeable Plugin]
4. xref:how-to-guides/plugin-development/publication/index.adoc[How to publish my plugin into the Aragon OSx protocol]
