name: Contracts-versions Tests
on:
  push:
    paths:
      - 'packages/contracts-versions/**'
      - '.github/workflows/contract-*.yml'

env:
  working-directory: packages/contracts-versions

jobs:
  test-hardhat:
    if: github.actor != 'arabot-1'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{env.working-directory}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0
      - name: Install node
        uses: actions/setup-node@v3
        with:
          cache: 'yarn'
          node-version: 16
      - name: Install dependencies
        run: cd ../../ && yarn install --pure-lockfile
      - name: Compile contracts-versions
        run: yarn run build
      - name: Run Tests
        run: yarn run test
