name: Mythx Changed only

on:
  workflow_dispatch:
    inputs:
      mode:
        description: "Mythx scan mode (quick|standard|deep)"
        required: true
        default: standard
        type: choice
        options:
          - quick
          - standard
          - deep

jobs:
  mythx:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - uses: actions/setup-python@v4
      - name: Install mythx-cli
        run: pip install mythx-cli
      - id: files
        uses: jitterbit/get-changed-files@v1
      - name: Install deps
        run: yarn
      - name: Run mythx
        run: mythx --ci --yes --api-key ${{ secrets.MYTHX_API_KEY }} analyze --mode ${{ inputs.mode }} ${{ steps.files.outputs.all }}