name: Mythx Full

on:
  workflow_call:
    inputs:
      mode:
        description: "Mythx scan mode (quick|standard|deep)"
        required: true
        type: string
    secrets:
      MYTHX_API_KEY:
        description: 'mythx api token'
        required: true
  workflow_dispatch:
    inputs:
      mode:
        description: "Mythx scan mode (quick|standard|deep)"
        required: true
        default: standard
        type: choice
        options:
          - quick
          - standard
          - deep
    

jobs:
  mythx:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - uses: actions/setup-python@v4
      - name: Install mythx-cli
        run: pip install mythx-cli
      - name: Install deps
        run: yarn
      - name: Run mythx
        run: mythx --output id --format json --yes --api-key ${{ secrets.MYTHX_API_KEY }} analyze --async --mode ${{ inputs.mode }} packages/contracts/contracts
      - name: SEE HERE FOR DASHBOARD LINK
        run: |
          id=$(cat id)
          group_id=$(mythx --format=json --api-key ${{ secrets.MYTHX_API_KEY }} analysis status $id | jq .group_id)
          echo "Scan started in group https://dashboard.mythx.io/#/console/analyses/groups/$group_id"