name: NPM Release

on:
  pull_request:
    types:
      - closed
    branches:
      - develop
      - main
    paths:
      - 'packages/contracts-ethers/**'
      - '.github/workflows/npm-release.yml'
      - '.github/workflows/npm-release-reusable.yml'

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      run: ${{ steps.checkSrc.outputs.run }}
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            contracts:
              - 'packages/contracts/**'
              - '.github/workflows/contracts-deploy.yml'
      - if: steps.changes.outputs.src == 'false'
        id: checkSrc
        run: echo "run=true" >> $GITHUB_OUTPUT
  npmDeploy:
    needs: ['check']
    if: needs.check.outputs.run != true
    uses: './.github/workflows/npm-release-reusable.yml'
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      ARABOT_PAT: ${{ secrets.ARABOT_PAT }}